package org.dav.service.view;

public enum ExtensionInfoType
{
	SPECIFICATION_TITLE,
	SPECIFICATION_VERSION,
	SPECIFICATION_VENDOR,
	IMPLEMENTATION_TITLE,
	IMPLEMENTATION_VERSION,
	IMPLEMENTATION_VENDOR
}
